### ISSUE TITLE
你好，请问evaluation里的pb_model应该选择什么？

### ISSUE THREAD

**Issue by lpl22-github** [huanghuidmml/cail2019_track2#5]
我做了预训练和训练，在ckpt和ckpt_pretrain里面并没有找到合适的 pb_model="pb/model.pb"文件

**Comment by HuiResearch** [comment]
这个pb文件是模型转换后的，我记得在convert里边吧，把ckpt转换成pb格式后再用




| |
m13021933043
邮箱：m13021933043@163.com
|

Signature is customized by Netease Mail Master

在2020年03月12日 19:06，lpl22-github 写道：

我做了预训练和训练，在ckpt和ckpt_pretrain里面并没有找到合适的 pb_model="pb/model.pb"文件

**Comment by lpl22-github** [comment]
> 这个pb文件是模型转换后的，我记得在convert里边吧，把ckpt转换成pb格式后再用 | | m13021933043 邮箱：m13021933043@163.com | Signature is customized by Netease Mail Master 在2020年03月12日 19:06，lpl22-github 写道： 我做了预训练和训练，在ckpt和ckpt_pretrain里面并没有找到合适的 pb_model="pb/model.pb"文件 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

解决了，谢谢：）
